// src/constants/GlossaryTableSort.js
export const GLOSSARY_TABLE_SORT_KEYS = Object.freeze({ TERM: "TERM", EXPLANATION_LENGTH: "EXPLANATION_LENGTH", DIRECT_NEIGHBOR_COUNT: "DIRECT_NEIGHBOR_COUNT", MASTERY: "MASTERY" });
export const GLOSSARY_TABLE_SORT_DIRECTIONS = Object.freeze({ ASCENDING: "ASCENDING", DESCENDING: "DESCENDING" });
